# nginx-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
  namespace: default # Match your PVC's namespace
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      include mime.types;
      default_type application/octet-stream;
      sendfile on;
      keepalive_timeout 65;
      server {
        listen 1234; # Nginx will listen on this port
        location / {
          root /usr/share/nginx/html; # Serve files from this path
          index index.html index.htm;
        }
      }
    }
